# version: '3.8'

# services:
#   opensis-db:
#     image: mariadb:10.5
#     container_name: opensis-db
#     restart: always
#     networks:
#       - opensis_network
#     environment:
#       MYSQL_ROOT_PASSWORD: my-secret-pw
#       MYSQL_DATABASE: openSIS
#       MYSQL_USER: openSIS_rw
#       MYSQL_PASSWORD: Op3nS!S
#     ports:
#       - "3304:3306"
#     volumes:
#       - db_data:/var/lib/mysql
#       - ./MYSQL/mysql-config/strict_mode.cnf:/etc/mysql/conf.d/my.cnf

#   opensis-ui:
#     image: opensis-ui
#     container_name: opensis-ui
#     restart: always
#     networks:
#       - opensis_network
#     ports:
#       - "8080:80"

#   db-init:
#     image: mariadb:10.5
#     container_name: db-init
#     restart: on-failure
#     networks:
#       - opensis_network
#     depends_on:
#       - opensis-db
#     volumes:
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#     entrypoint: ["bash", "-c", "sleep 10 && mysql -h opensis-db -u root -pmy-secret-pw < /docker-entrypoint-initdb.d/init.sql"]

# networks:
#   opensis_network:
#     driver: bridge

# volumes:
#   db_data:

# # Ensure init.sql exists in the same directory as this file with the following content:
# # CREATE DATABASE openSIS DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
# # GRANT ALL PRIVILEGES ON *.* TO 'openSIS_rw'@'%' IDENTIFIED BY 'Op3nS!S' WITH GRANT OPTION;
# # FLUSH PRIVILEGES;



version: '3.8'

services:
  opensis-db:
    image: mariadb:10.5
    container_name: opensis-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "secrets#$"
      MYSQL_DATABASE: "openSIS"
      MYSQL_USER: "openSIS_rw"
      MYSQL_PASSWORD: "Op3nS!S"
    volumes:
      - db_data:/var/lib/mysql  # Persist database data
      - ./MYSQL/mysql-init:/docker-entrypoint-initdb.d  # Init scripts -Stores initialization scripts for first-time setup.
      - ./MYSQL/mysql-config:/etc/mysql/conf.d/strict_mode.cnf  # Custom MySQL config -Ensures strict mode is disabled
    networks:
      opensis-nw:
        aliases:
          - opensis

  opensis-ui:
    image: opensis-i
    container_name: opensis-ui
    depends_on:
      - opensis-db
    ports:
      - "8080:80"
    networks:
      opensis-nw:
        aliases:
          - opensis

networks:
  opensis-nw:
    driver: bridge

volumes:
  db_data:  # Named volume for MariaDB persistence
